# config/packages/security.yaml
security:
    firewalls:
        main:
            pattern:   ^/api
            stateless: true
            jwt: ~
            #access_token:
                #token_handler: App\Security\AccessTokenHandler

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    access_control:
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }          
